apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"
      queryTimeout: "60s"
      httpMethod: "POST"
    version: 1

  - name: AlertManager
    type: alertmanager
    access: proxy
    url: http://alertmanager:9093
    editable: true
    jsonData:
      implementation: "prometheus"
    version: 1

  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "creative-identity-logs-*"
    jsonData:
      esVersion: "8.11.0"
      timeField: "@timestamp"
      interval: "Daily"
      maxConcurrentShardRequests: 5
    version: 1

  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: creative_identity_dev
    user: postgres
    secureJsonData:
      password: password
    jsonData:
      sslmode: "disable"
      postgresVersion: 1500
    version: 1

  - name: TimescaleDB
    type: postgres
    access: proxy
    url: timescaledb:5432
    database: creative_identity_analytics
    user: timescale
    secureJsonData:
      password: password
    jsonData:
      sslmode: "disable"
      postgresVersion: 1500
      timescaledb: true
    version: 1